// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHMSG8wxlbrGORU-X_Id9wzI6J4CI9ws8',
    appId: '1:1024997581907:web:92aaf8b02e6d0ff39092a6',
    messagingSenderId: '1024997581907',
    projectId: 'pharma-finder-6d99d',
    authDomain: 'pharma-finder-6d99d.firebaseapp.com',
    storageBucket: 'pharma-finder-6d99d.firebasestorage.app',
    measurementId: 'G-T65R27F0RN',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbra2FVcdy2ohw9m5PfzHrxyIrSWxz0k',
    appId: '1:1024997581907:android:aaab7ee25af3b8c99092a6',
    messagingSenderId: '1024997581907',
    projectId: 'pharma-finder-6d99d',
    storageBucket: 'pharma-finder-6d99d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQt9l8IVFlzuUfyM6hoc0SxndTOIZUdAM',
    appId: '1:1024997581907:ios:c0080b4dd37178659092a6',
    messagingSenderId: '1024997581907',
    projectId: 'pharma-finder-6d99d',
    storageBucket: 'pharma-finder-6d99d.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyWebApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQt9l8IVFlzuUfyM6hoc0SxndTOIZUdAM',
    appId: '1:1024997581907:ios:c0080b4dd37178659092a6',
    messagingSenderId: '1024997581907',
    projectId: 'pharma-finder-6d99d',
    storageBucket: 'pharma-finder-6d99d.firebasestorage.app',
    iosBundleId: 'com.example.pharmacyWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHMSG8wxlbrGORU-X_Id9wzI6J4CI9ws8',
    appId: '1:1024997581907:web:a9f77152d38266a29092a6',
    messagingSenderId: '1024997581907',
    projectId: 'pharma-finder-6d99d',
    authDomain: 'pharma-finder-6d99d.firebaseapp.com',
    storageBucket: 'pharma-finder-6d99d.firebasestorage.app',
    measurementId: 'G-8413LFGMZG',
  );
}
